### ISSUE TITLE
Precompiled gem for Ruby 3.2

### ISSUE THREAD

**Issue by jbourassa** [bytecodealliance/wasmtime-rb#103]
wasmtime-rb v0.4.1 works on Ruby 3.2, but requires compiling from source. The latest release aimed to solve that, but it didn't work: the `.gem` does not have a precompiled bundle for 3.2. After investigating, we are indeed including 3.2 in the list of rubies to precompile for (`ruby-versions: 2.7, 3.0, 3.1, 3.2`). I _think_ the culprit is `rake-compiler-dock` (RCD) not yet supporting Ruby 3.2.

We should be able to specify a [Docker image in a ENV var](https://github.com/rake-compiler/rake-compiler-dock/blob/db23ffdad2e14e168112c18f3484539565dbf77c/lib/rake_compiler_dock/starter.rb#L50-L53), similar to what Mike did for [SQLite](https://github.com/sparklemotion/sqlite3-ruby/pull/367/files) and [Nokogiri](https://github.com/sparklemotion/nokogiri/pull/2732/files). That, or wait until the next RCD release.

**Comment by jbourassa** [comment]
> We should be able to specify a [Docker image in a ENV var](https://github.com/rake-compiler/rake-compiler-dock/blob/db23ffdad2e14e168112c18f3484539565dbf77c/lib/rake_compiler_dock/starter.rb#L50-L53)

Hmm, I think that won't work: [rb-sys uses RCD's images](https://github.com/oxidize-rb/rb-sys/blob/e8d8d8b354f513688ece70d8c88aba31f3bbf3ee/docker/Dockerfile.x86-linux#L1) to build its own images, and then [injects those as `RCD_IMAGE`](https://github.com/oxidize-rb/cross-gem-action/blob/fb728aecc0c142ca4630177bdef7f9a09f99e080/src/setup.ts#L43).

**Comment by ianks** [comment]
Ruby 3.2 images are up now. Do they work?

**Comment by jbourassa** [comment]
Yes it works, I just need to cut a release now. I'm planning on release v5.0.0 with when Wasmtime 5.0 hits which should be around the 20th.

**Comment by jbourassa** [comment]
Fixed as of v5.0.0!
