### ISSUE TITLE
Upgrade to magnus v0.6.1

### ISSUE THREAD

**Issue by ianks** [bytecodealliance/wasmtime-rb#215]
[Here's the changelog](https://github.com/matsadler/magnus/blob/main/CHANGELOG.md#060---2023-07-28) for reference.

Please claim this issue by commenting below 👇🏻

**Comment by ggmichaelgo** [comment]
@Youssef-Mak and @ggmichaelgo has started this task 👍

**Comment by jbourassa** [comment]
Make sure to have a look at #205, Mat took a stab at it already.

**Comment by jbourassa** [comment]
Fixed in #205
