### ISSUE TITLE
wasmtime gem is not fully published

### ISSUE THREAD

**Issue by glebpom** [bytecodealliance/wasmtime-rb#298]
According to rubygems, wasmtime 17.0.1 is published only for `aarch64-linux`

https://rubygems.org/gems/wasmtime

**Comment by saulecabrera** [comment]
Thanks for the report, all versions are now up-to-date. For some reason the release job failed. https://rubygems.org/gems/wasmtime/versions. I'm going to close this, but feel free to follow-up here if anything is still not working as expected.
