### ISSUE TITLE
`Publish doc` and `Post Publish doc` actions consistently failing

### ISSUE THREAD

**Issue by saulecabrera** [bytecodealliance/wasmtime-rb#377]
I haven't done a deep investigation here, however I've seen consistent failures in the `Publish doc` and `Post Publish doc` actions on main. I'm not entirely sure what's causing them. Here's a screenshot of the failure:

<img width="1110" alt="Screenshot 2024-09-20 at 5 16 02 PM" src="https://github.com/user-attachments/assets/599e358a-265d-42fd-bec9-52041d2be654">

**Comment by jbourassa** [comment]
I'll have a look. I enabled the publish doc action in the release workflow without knowing for sure it'd work.
