### ISSUE TITLE
Wasmtime::WasiCtxBuilder not available from Ruby

### ISSUE THREAD

**Issue by jkehres** [bytecodealliance/wasmtime-rb#80]
I tried running the example from `examples/wasi.rb` but I got the following error:

`uninitialized constant Wasmtime::WasiCtxBuilder (NameError)`

Looking at the classes available in the `Wasmtime` module, `WasiCtxBuilder` appears to be missing. I ran the following command to see what classes were available:

` Wasmtime.constants.select { |c| Wasmtime.const_get(c).is_a? Class }.sort`

which produced the following list:

```
[
  :Caller,
  :Config,
  :ConversionError,
  :Engine,
  :Error,
  :Extern,
  :Func,
  :FuncType,
  :Instance,
  :Linker,
  :Memory,
  :MemoryType,
  :Module,
  :Store, 
  :Trap
]
```

I used version `0.3.0` of the gem on `arm64-darwin`.

**Comment by jkehres** [comment]
Oops. I was looking at the examples in main. Looks like a gem with WASI support hasn't been released yet. Never mind.

**Comment by jbourassa** [comment]
I'll try and cut a release soon with all the new features that have been added. Meanwhile you should be able to install from git with bundler, assuming you have a Rust compiler.

Best of luck!
